version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: |
            version="$CIRCLE_SHA1"
            # Remove any characters that are invalid in Docker image tags
            version=$(echo "$version" | tr -cd '[:lower:][:digit:]-')
            echo $version
            docker build -t bhanuprakshnrb/circle-ci-app:$version .
            docker images
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"  --password-stdin
            docker push "bhanuprakshnrb/circle-ci-app:$version"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build

