version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: |
            docker build -t my-python-app:latest .
            docker images
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker tag my-python-app:latest "$DOCKER_USERNAME/my-python-app:latest"
            docker push "$DOCKER_USERNAME/my-python-app:latest"

  

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
     


