version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t new-python-app:$version .
            docker images
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker tag new-python-app:$version "$DOCKER_USERNAME/new-python-app:$version"
            docker push "$DOCKER_USERNAME/new-python-app:$version"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
