version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: |
            docker build -t my-python-app:latest .
            docker images
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker tag my-python-app:latest "$DOCKER_USERNAME/my-python-app:latest"
            docker push "$DOCKER_USERNAME/my-python-app:latest"

  deploy-argocd:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install ArgoCD CLI
          command: |
            sudo wget https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 -O /usr/local/bin/argocd
            sudo chmod +x /usr/local/bin/argocd
            argocd version
      - run:
          name: Login to ArgoCD
          command: |
            argocd login --username "$ARGOCD_USERNAME" --password "$ARGOCD_PASSWORD" --server "$ARGOCD_SERVER"
      - run:
          name: Deploy ArgoCD Application
          command: |
            argocd app create my-app --repo https://github.com/your-repo.git --path ./argocd-app --dest-server https://kubernetes.default.svc --dest-namespace default
            argocd app sync my-app

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-argocd:
          requires:
            - build


