name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          version="${GITHUB_SHA::8}"
          echo "$version"
          docker build -t bhanunr/santhosha123:"$version" .
          docker images
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u bhanunr --password-stdin docker.io
          docker tag bhanunr/santhosha123:"$version" bhanunr/santhosha12:"$version"
          docker push bhanunr/santhosha12:"$version"
