name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

     

      - name: Install test dependencies
        run: |
          pip install pytest

      - name: Run tests
        run: |
          pytest

  build_and_push_docker:
    runs-on: ubuntu-latest

    needs: build_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          version="${GITHUB_SHA::8}"
          docker build -t myapp:"$version" .
          docker images

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin docker.io

      - name: Tag and push Docker image
        run: |
          version="${GITHUB_SHA::8}"
          docker tag myapp:"$version" "${{ secrets.DOCKER_USERNAME }}/myapp:"$version"
          docker push "${{ secrets.DOCKER_USERNAME }}/myapp:"$version"
