name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
         #Install Minikube and configure kubectl
      - name: Install Minikube and configure kubectl
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/
          minikube start --driver=docker
          kubectl config use-context minikube  
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p '*_test.py' || true

  build_and_deploy:
    runs-on: ubuntu-latest

    needs: build_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          version="${GITHUB_SHA::8}"
          echo "$version"
          docker build -t git-ci-app:"$version" .
          docker images
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u bhanunr --password-stdin docker.io
          docker tag git-ci-app:"$version" bhanunr/santhosha12:"$version"
          docker push bhanunr/santhosha12:"$version"


      - name: Deploy application to Minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f services.yaml         
